### ISSUE TITLE
Easy way to add a private CA certificate to java cacerts

### ISSUE THREAD

**Issue by jamshid** [mattgruter/dockerfile-artifactory#7]
I assume I need to add a private CA to the java keystore, to avoid this error when adding a remote repository (https://www.jfrog.com/confluence/display/RTF/Configuring+Repositories) like https://private.example.com/maven/repository/snapshots/. 
```
Connection failed with exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
I tried creating a Dockerfile `FROM mattgruter/artifactory` with these additional steps:
``` 
ENV JAVA_CACERTS /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security/cacerts 
ADD MYCOMPANY_CA.pem ./ 
RUN keytool -noprompt -storepass changeit -keystore ${JAVA_CACERTS} -import -file MYCOMPANY_CA.pem -alias MYCOMPANY_CA 
``` 
but that didn't work because the ONBUILD step failed.
So, I just copied your Dockerfile and commented out the ONBUILD. Don't know of a better solution, maybe the ability to pass extra CA's via env var?

Unfortunately, artifactory still doesn't accept my private repo. I verified a simple java URL() request to  https://private.example.com/maven/repository/snapshots/ fails before adding the private CA, and works after, so I guess I don't understand what `cacerts` artifactory is using. Anybody know?

**Comment by mattgruter** [comment]
I haven't been able to get this to work yet either. Have you made any progress?

PS: I just removed the `ONBUILD` trigger from the Dockerfile (moved it to a seperate image) so you don't have to uncomment that line anymore.

**Comment by jamshid** [comment]
Thanks. Sorry, no progress. I did file this bug with artifactory but there's been no response.
https://www.jfrog.com/jira/browse/RTFACT-7438

**Comment by jamshid** [comment]
Hi, thanks but I guess I'll close this. FYI JFrog appears to be maintaining a docker image now and it contains a new version. Updating /etc/pki/java/cacerts there does work. I am able to add a private https repository whose certificate is signed by a private certificate authority -- their admin console accepts it as a new repository. 

Unfortunately, artifactory still fails to download from my private repo, so I have exclude it with `pom.xml` config:

      <mirrorOf>*,!example.internal.snapshots,!example.internal</mirrorOf>

Here's the Dockerfile I'm using to add my CA certificate:

```
# Build cache for maven repos, configured to allow repository https://private.example.com
FROM jfrog-docker-registry.bintray.io/artifactory/artifactory-oss
# Expose Artifactories data, log and backup directory.
VOLUME /artifactory/data
VOLUME /artifactory/logs
VOLUME /artifactory/backup

ENV JAVA_CACERTS /etc/pki/java/cacerts
ADD Example_CA.pem /etc/ssl/certs/
RUN keytool -noprompt -storepass changeit -keystore ${JAVA_CACERTS} -import -file /etc/ssl/certs/Example_CA.pem -alias Example_CA
```
